### ISSUE TITLE
link conf directory on windows

### ISSUE THREAD

**Issue by robertzych** [vrivellino/chef-java_se#17]
Please add the following to _windows_install.rb:

`link "#{javalink_dir}\\conf" do
  to "#{java_home}\\conf"
end`

This link resolves an installation error I was having with another java app. I can reproduce that error and attach the details if you'd like.

**Comment by vrivellino** [comment]
@robertzych: Is this needed just for Java 10, or should it be added for Java 8 as well?

**Comment by robertzych** [comment]
@vrivellino: When are you planning to release the next version of this cookbook?

**Comment by vrivellino** [comment]
@robertzych: Oracle released Java 11, which appears to be their new LTS version, and it looks like Java 10 is now EOL'd. That said, this fix is in 11.0.1 of this cookbook.
